DELETE http://localhost:8080/actions/13
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imcuc2FyYmFqQGljbG91ZC5jb20iLCJleHAiOjE3MzEzMjgzMTksInVzZXJJZCI6Mn0.V619NmBZhpSCpGbrVEo3DVZiHdVf9zhlovwGCh8E6aI