PUT http://localhost:8080/actions/11
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imcuc2FyYmFqQGljbG91ZC5jb20iLCJleHAiOjE3MzEzMjgzMTksInVzZXJJZCI6Mn0.V619NmBZhpSCpGbrVEo3DVZiHdVf9zhlovwGCh8E6aI

{
  "Name": "Test Action Updated",
  "Description": "Test Action description Updated",
  "Location": "Test location updated",
  "DateTime": "2025-06-03T15:35:00.000Z"
}